apiVersion: apps/v1
kind: Deployment
metadata:
  name: bopeep-frontend
  labels:
    app: bopeep-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bopeep-frontend
  template:
    metadata:
      labels:
        app: bopeep-frontend
    spec:
      containers:
        - name: bopeep-frontend
          image: julianv08/bopeep-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
