import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import { Separator } from '@/components/ui/separator';
import { AppSidebar } from "@/components/sideBar/page";
import Header from "@/components/header/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="h-screen">
            {/* Navbar siempre arriba */}
            {/* Contenido principal con Sidebar */}
            <SidebarProvider>
                {/* Sidebar */}
                <SidebarInset>
                    <div className="flex flex-row justify-start">
                        <AppSidebar />
                        {/* Contenido */}
                        <div className='w-full'>
                            <header className="flex shrink-0 items-center gap-2 border-b bg-gray-200">
                                <div className="flex flex-fill justify-between items-center gap-2 px-3 w-full">
                                    <div className="flex items-center gap-2">
                                        <SidebarTrigger />
                                        <Separator orientation="vertical" className="h-1 bg-gray-200" />
                                    </div>
                                    <Header className="flex-grow" />
                                </div>
                            </header>
                            <main className="flex-1">
                                {children}
                            </main>
                        </div>
                    </div>
                </SidebarInset>
            </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
